services:
  shinyproxy:
    image: openanalytics/shinyproxy:3.2.2
    container_name: shinyproxy
    restart: unless-stopped
    volumes:
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml:ro
      - ./shinyproxy/users.yml:/opt/shinyproxy/users.yml:ro
      - ./shinyproxy/templates/:/opt/shinyproxy/templates/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - ${DOCKER_GID}
    ports:
      - 8080:8080
    networks:
      - shinyproxy-nw
networks:
  shinyproxy-nw:
    name: shinyproxy-nw
    external: true
