###########################
# SETTINGS FOR SHINYPROXY #
###########################
proxy:
  ##########################
  # DO NOT CHANGE ANYTHING #
  ##########################
  title: San Camillo Apps
  logo-url: file:///opt/shinyproxy/templates/assets/img/logo_sc/sancamillo_logo_white.png
  favicon-path: /opt/shinyproxy/templates/assets/img/favicon/favicon.ico
  port: 8080
  template-path: ./templates/
  authentication: none
  admin-groups: admins
  docker:
      internal-networking: true
  template-groups:
    - id: clinical
      properties:
        display-name: Clinical Support
        display-name_it: Supporto Clinico
    - id: scientific
      properties:
        display-name: Scientific Communication
        display-name_it: Lavori Scientifici

# External files
# spring:
#   config:
#     import:
#       - users.yml

  ###############################
  # CHANGE HERE TO ADD NEW APPS #
  ###############################
  specs:
  - id: MOCAv3
    display-name: MOCA v3
    description: Normative data for MOCA considering Age, Education, CRI, and Sex.
    docker-cmd: ["R", "-e", "shiny::runApp('/root/mocav3')"]
    container-image: shinyapp-mocav3
    container-network: shinyproxy-nw
    minimum-seats-available: 5
    seats-per-container: 20
    logo-url: /assets/img/apps/MOCAv3.png
    template-group: clinical
    template-properties:
      author: Giorgio Arcara
      contact: giorgio.arcara@hsancamillo.it
      article: "Cognitive reserve estimated with a life experience questionnaire outperforms education in predicting performance on MoCA: Italian normative data."
      doi: 10.1007/s12144-022-03062-6
      description_it: Data normativi per MOCA considerando Età, Educazione, CRI e Sesso.
  - id: erp-kw-osc
    display-name: Mapping ERP amplitudes on form-to-meaning computations
    description: Visualizing the interplay between Orthography- and Phonology-Semantics Consistency (OSC and PSC) and ERP amplitude during a lexical decision task.
    docker-cmd: ["R", "-e", "shiny::runApp('/root/erp-kw-osc')"]
    container-image: shinyapp-erpkwosc
    container-network: shinyproxy-nw
    minimum-seats-available: 5
    seats-per-container: 20
    logo-url: /assets/img/apps/ERP_KW_OSC_PSC.png
    template-group: scientific
    template-properties:
      author: Sara Lago
      contact: sara.lago@hsancamillo.it
      article: "Very early and late form-to-meaning computations during visual word recognition as revealed by electrophysiology"
      doi: 10.1016/j.cortex.2022.07.016
      display-name_it: ERPs e mappaggio grafema-fonema
      description_it: Visualizzazione delle interazioni tra consistenza ortografico- e fonemico-semantica e ampiezza ERP durante un compito di decisione lessicale
  - id: gamm
    display-name: Education, EEG Aperiodic Components and Cognitive Aging
    description: Interactive visualization of non-linear relationships between aperiodic EEG components, age and education
    docker-cmd: ["R", "-e", "shiny::runApp('/root/gamm')"]
    container-image: shinyapp-gamm
    container-network: shinyproxy-nw
    minimum-seats-available: 5
    seats-per-container: 20
    logo-url: /assets/img/apps/GAMM.png
    template-group: scientific
    template-properties:
      author: Sara Lago
      contact: sara.lago@hsancamillo.it
      display-name_it: Scolarità, componenti aperiodiche dello spettro EEG e invecchiamento cognitivo
      description_it: Visualizzazione interattiva delle relazioni non lineari tra scolarità, componenti aperiodiche dello spettro EEG e invecchiamento cognitivo
  - id: sens-spec
    display-name: Sensitivity, Specificty and Roc explorer for neuropsychological tests
    description: An app designed to help users learn and explore statistical concepts in clinical neuropsychology. It allows users to simulate data and examine how classifications based on cut-off scores influence diagnostic performance, depending on the underlying data properties.
    docker-cmd: ["R", "-e", "shiny::runApp('/root/sens-spec')"]
    container-image: shinyapp-sens-spec
    container-network: shinyproxy-nw
    minimum-seats-available: 5
    seats-per-container: 20
    logo-url: /assets/img/apps/sens-spec.png
    template-group: scientific
    template-properties:
      author: Giorgio Arcara
      contact: giorgio.arcara@hsancamillo.it
      display-name_it: Sensitività, Specificità e ROC per test neuropsicologici
      description_it: Un'app progettata per aiutare gli utenti ad apprendere ed esplorare i concetti statistici nella neuropsicologia clinica. Consente agli utenti di simulare dati ed esaminare come le classificazioni basate sui punteggi di cut-off influenzano le prestazioni diagnostiche, a seconda delle proprietà dei dati sottostanti.


logging:
  file:
    name: shinyproxy.log
